name: Maven CI/CD Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: [self-hosted]

    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install Maven
        run: |
          MAVEN_VERSION=3.9.6
          curl -fsSL https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz -o maven.tar.gz
          tar -xzf maven.tar.gz
          sudo mv apache-maven-${MAVEN_VERSION} /opt/maven
          echo "/opt/maven/bin" >> $GITHUB_PATH
          export PATH=/opt/maven/bin:$PATH
          mvn -v

      - name: Build and test project with Maven
        run: |
          export PATH=/opt/maven/bin:$PATH
          mvn -B package --file pom.xml

  publish-job:
    runs-on: [self-hosted]
    needs: build_and_test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Re-install Maven
        run: |
          MAVEN_VERSION=3.9.6
          curl -fsSL https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz -o maven.tar.gz
          tar -xzf maven.tar.gz
          sudo mv apache-maven-${MAVEN_VERSION} /opt/maven
          echo "/opt/maven/bin" >> $GITHUB_PATH
          export PATH=/opt/maven/bin:$PATH
          mvn -v

      - name: Build for publish
        run: |
          export PATH=/opt/maven/bin:$PATH
          mvn -B package --file pom.xml -DskipTests
          mkdir -p staging
          cp target/*jar-with-dependencies.jar staging || cp target/*.jar staging

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
          

