name: Maven CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: [self-hosted]

    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4

      - name: Install JDK 14 manually
        run: |
          mkdir -p $HOME/java14
          curl -fsSL https://archive.org/download/jdk-14.0.2+12/OpenJDK14U-jdk_x64_linux_hotspot_14.0.2_12.tar.gz -o jdk14.tar.gz
          tar -xzf jdk14.tar.gz -C $HOME/java14 --strip-components=1
          echo "JAVA_HOME=$HOME/java14" >> $GITHUB_ENV
          echo "$HOME/java14/bin" >> $GITHUB_PATH
          java -version

      - name: Install Maven 3.9.5
        run: |
          MAVEN_VERSION=3.9.5
          curl -fsSL https://dlcdn.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz -o maven.tar.gz
          tar -xzf maven.tar.gz -C $HOME
          echo "$HOME/apache-maven-${MAVEN_VERSION}/bin" >> $GITHUB_PATH
          mvn -version

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and test with Maven
        run: mvn -B package --file pom.xml

  publish-job:
    runs-on: [self-hosted]
    needs: [build_and_test]

    steps:
      - uses: actions/checkout@v4

      - name: Reuse JDK & Maven
        run: |
          echo "$HOME/java14/bin" >> $GITHUB_PATH
          echo "$HOME/apache-maven-3.9.5/bin" >> $GITHUB_PATH
          java -version
          mvn -version
          mvn -B package --file pom.xml -DskipTests

      - name: Prepare artifact
        run: |
          mkdir -p staging
          cp target/*jar-with-dependencies.jar staging/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
