name: Maven CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: [self-hosted]

    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 14 (Zulu)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '14'
          cache: 'maven'

      - name: Install Maven (if not already installed)
        run: |
          MAVEN_VERSION=3.9.6
          curl -fsSL https://downloads.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz -o maven.tar.gz
          tar -xzf maven.tar.gz
          sudo mv apache-maven-${MAVEN_VERSION} /opt/maven
          echo "export PATH=/opt/maven/bin:\$PATH" >> $HOME/.bashrc
          export PATH=/opt/maven/bin:$PATH
          mvn -version

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and test with Maven
        run: |
          export PATH=/opt/maven/bin:$PATH
          mvn -B package --file pom.xml


  publish-job:
    runs-on: [self-hosted]
    needs: [build_and_test]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 14 (Zulu)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '14'
          cache: 'maven'

      - name: Export Maven Path
        run: |
          export PATH=/opt/maven/bin:$PATH
          mvn -version

      - name: Build without tests
        run: |
          export PATH=/opt/maven/bin:$PATH
          mvn -B package --file pom.xml -DskipTests

      - name: Prepare artifact
        run: |
          mkdir staging
          cp target/*jar-with-dependencies.jar staging

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
